// Variants/Trims for popular models (brand -> model -> variants)
export const carVariants: Record<string, Record<string, string[]>> = {
  // Luxury & Exotic
  "Lamborghini": {
    "Huracán": ["EVO", "EVO Spyder", "Performante", "STO", "Tecnica", "Sterrato"],
    "Urus": ["S", "Performante", "SE"],
    "Aventador": ["S", "SVJ", "Ultimae", "LP 700-4", "LP 750-4 SV"],
    "Revuelto": ["Standard"],
  },
  "Ferrari": {
    "296 GTB": ["Standard", "Assetto Fiorano"],
    "296 GTS": ["Standard", "Assetto Fiorano"],
    "SF90 Stradale": ["Standard", "Spider", "XX Stradale"],
    "F8 Tributo": ["Standard", "Spider"],
    "Roma": ["Standard", "Spider"],
    "Purosangue": ["Standard"],
    "812 Superfast": ["Standard", "GTS", "Competizione"],
  },
  "Porsche": {
    "911": ["Carrera", "Carrera S", "Carrera 4", "Carrera 4S", "Carrera GTS", "Turbo", "Turbo S", "GT3", "GT3 RS", "GT3 Touring", "Targa 4", "Targa 4S", "Dakar"],
    "718 Cayman": ["Standard", "S", "GTS 4.0", "GT4", "GT4 RS"],
    "718 Boxster": ["Standard", "S", "GTS 4.0", "Spyder", "Spyder RS"],
    "Panamera": ["Standard", "4", "4S", "GTS", "Turbo", "Turbo S", "4 E-Hybrid", "Turbo S E-Hybrid"],
    "Taycan": ["Standard", "4S", "GTS", "Turbo", "Turbo S", "Cross Turismo"],
    "Macan": ["Standard", "S", "GTS", "Turbo", "T", "Electric"],
    "Cayenne": ["Standard", "S", "GTS", "Turbo", "Turbo GT", "E-Hybrid", "Turbo S E-Hybrid"],
  },
  "McLaren": {
    "750S": ["Coupé", "Spider"],
    "720S": ["Coupé", "Spider"],
    "765LT": ["Coupé", "Spider"],
    "Artura": ["Standard", "Spider"],
    "GT": ["Standard"],
  },
  "Aston Martin": {
    "DB11": ["V8", "V12", "AMR"],
    "DB12": ["Coupé", "Volante"],
    "DBS": ["Superleggera", "770 Ultimate"],
    "Vantage": ["V8", "F1 Edition", "Roadster"],
    "DBX": ["Standard", "707"],
  },
  "Bentley": {
    "Continental GT": ["V8", "Speed", "Mulliner", "S"],
    "Continental GTC": ["V8", "Speed", "Mulliner", "S"],
    "Flying Spur": ["V8", "Speed", "Mulliner", "Hybrid"],
    "Bentayga": ["V8", "Speed", "EWB", "S", "Hybrid"],
  },
  "Rolls-Royce": {
    "Phantom": ["Standard", "EWB", "Series II"],
    "Ghost": ["Standard", "EWB", "Black Badge"],
    "Cullinan": ["Standard", "Black Badge"],
    "Spectre": ["Standard"],
    "Wraith": ["Standard", "Black Badge"],
    "Dawn": ["Standard", "Black Badge"],
  },
  // Premium German
  "Mercedes-Benz": {
    "A-Klasse": ["A 180", "A 200", "A 220", "A 250", "A 250 e", "A 35 AMG", "A 45 AMG", "A 45 S AMG"],
    "B-Klasse": ["B 180", "B 200", "B 220", "B 250 e"],
    "C-Klasse": ["C 180", "C 200", "C 220 d", "C 300", "C 300 d", "C 300 e", "C 43 AMG", "C 63 AMG", "C 63 S AMG"],
    "E-Klasse": ["E 200", "E 220 d", "E 300", "E 300 d", "E 300 e", "E 400 d", "E 450", "E 53 AMG", "E 63 AMG", "E 63 S AMG"],
    "S-Klasse": ["S 350 d", "S 400 d", "S 450", "S 500", "S 580", "S 580 e", "S 63 AMG", "S 680 Maybach"],
    "CLA": ["CLA 180", "CLA 200", "CLA 220", "CLA 250", "CLA 35 AMG", "CLA 45 AMG", "CLA 45 S AMG"],
    "CLE": ["CLE 200", "CLE 300", "CLE 450", "CLE 53 AMG"],
    "GLA": ["GLA 180", "GLA 200", "GLA 220", "GLA 250", "GLA 35 AMG", "GLA 45 AMG", "GLA 45 S AMG"],
    "GLB": ["GLB 180", "GLB 200", "GLB 220", "GLB 250", "GLB 35 AMG"],
    "GLC": ["GLC 200", "GLC 220 d", "GLC 300", "GLC 300 d", "GLC 300 e", "GLC 400 d", "GLC 43 AMG", "GLC 63 AMG", "GLC 63 S AMG"],
    "GLE": ["GLE 300 d", "GLE 350 d", "GLE 400 d", "GLE 450", "GLE 580", "GLE 53 AMG", "GLE 63 AMG", "GLE 63 S AMG"],
    "GLS": ["GLS 350 d", "GLS 400 d", "GLS 450", "GLS 580", "GLS 63 AMG", "GLS 600 Maybach"],
    "G-Klasse": ["G 400 d", "G 500", "G 63 AMG"],
    "EQA": ["EQA 250", "EQA 300", "EQA 350"],
    "EQB": ["EQB 250", "EQB 300", "EQB 350"],
    "EQC": ["EQC 400"],
    "EQE": ["EQE 300", "EQE 350", "EQE 500", "EQE 43 AMG", "EQE 53 AMG"],
    "EQS": ["EQS 450", "EQS 500", "EQS 580", "EQS 53 AMG", "EQS 680 Maybach"],
    "AMG GT": ["43", "53", "55", "63", "63 S", "Black Series"],
    "SL": ["SL 43", "SL 55", "SL 63"],
  },
  "BMW": {
    "1er": ["116i", "118i", "120i", "128ti", "M135i xDrive"],
    "2er": ["218i", "220i", "223i", "M235i xDrive"],
    "3er": ["318i", "320i", "320d", "330i", "330d", "330e", "M340i", "M340d"],
    "4er": ["420i", "420d", "430i", "430d", "M440i"],
    "5er": ["520i", "520d", "530i", "530d", "530e", "540i", "540d", "M550i"],
    "7er": ["735i", "740i", "740d", "750e", "760i", "i7 xDrive60", "M760e"],
    "8er": ["840i", "840d", "M850i"],
    "X1": ["sDrive18i", "sDrive20i", "xDrive20i", "xDrive23i", "xDrive25e", "M35i"],
    "X2": ["sDrive18i", "sDrive20i", "xDrive20i", "xDrive25e", "M35i"],
    "X3": ["sDrive20i", "xDrive20i", "xDrive20d", "xDrive30i", "xDrive30d", "xDrive30e", "M40i", "M40d"],
    "X4": ["xDrive20i", "xDrive20d", "xDrive30i", "xDrive30d", "M40i", "M40d"],
    "X5": ["xDrive40i", "xDrive40d", "xDrive45e", "xDrive50e", "M50i", "M60i"],
    "X6": ["xDrive40i", "xDrive40d", "M50i", "M60i"],
    "X7": ["xDrive40i", "xDrive40d", "M60i"],
    "iX": ["xDrive40", "xDrive50", "M60"],
    "iX1": ["xDrive30"],
    "iX3": ["Standard"],
    "i4": ["eDrive35", "eDrive40", "M50"],
    "i5": ["eDrive40", "M60 xDrive"],
    "i7": ["xDrive60", "M70 xDrive"],
    "Z4": ["sDrive20i", "sDrive30i", "M40i"],
    "M2": ["Standard", "Competition"],
    "M3": ["Standard", "Competition", "CS", "Touring"],
    "M4": ["Standard", "Competition", "CS", "CSL"],
    "M5": ["Standard", "Competition", "CS"],
    "M8": ["Competition", "Competition Gran Coupé"],
  },
  "Audi": {
    "A1": ["25 TFSI", "30 TFSI", "35 TFSI", "40 TFSI"],
    "A3": ["30 TFSI", "35 TFSI", "35 TDI", "40 TFSI", "40 TDI", "45 TFSI e", "S3", "RS 3"],
    "A4": ["35 TFSI", "40 TFSI", "40 TDI", "45 TFSI", "50 TDI", "S4", "RS 4"],
    "A5": ["35 TFSI", "40 TFSI", "40 TDI", "45 TFSI", "S5", "RS 5"],
    "A6": ["40 TFSI", "45 TFSI", "40 TDI", "45 TDI", "50 TDI", "55 TFSI e", "S6", "RS 6"],
    "A7": ["45 TFSI", "50 TDI", "55 TFSI e", "S7", "RS 7"],
    "A8": ["50 TDI", "55 TFSI", "60 TFSI e", "S8"],
    "Q2": ["30 TFSI", "35 TFSI", "35 TDI", "SQ2"],
    "Q3": ["35 TFSI", "40 TFSI", "35 TDI", "45 TFSI e", "RS Q3"],
    "Q4 e-tron": ["35", "40", "45", "50", "Sportback"],
    "Q5": ["40 TFSI", "45 TFSI", "40 TDI", "50 TDI", "55 TFSI e", "SQ5"],
    "Q7": ["45 TFSI", "50 TDI", "55 TFSI e", "60 TFSI e", "SQ7"],
    "Q8": ["50 TDI", "55 TFSI", "60 TFSI e", "SQ8", "RS Q8"],
    "e-tron": ["50", "55", "S", "GT", "RS e-tron GT"],
    "TT": ["40 TFSI", "45 TFSI", "TTS", "TT RS"],
    "R8": ["V10", "V10 Performance", "V10 GT"],
  },
  "Volkswagen": {
    "Polo": ["1.0 TSI", "1.0 TSI DSG", "GTI"],
    "Golf": ["1.0 TSI", "1.5 TSI", "2.0 TDI", "1.4 eHybrid", "GTI", "GTI Clubsport", "GTD", "GTE", "R"],
    "ID.3": ["Pure", "Pro", "Pro S", "GTX"],
    "ID.4": ["Pure", "Pro", "Pro S", "GTX"],
    "ID.5": ["Pro", "Pro S", "GTX"],
    "ID.7": ["Pro", "Pro S", "GTX"],
    "Passat": ["1.5 TSI", "2.0 TSI", "2.0 TDI", "1.4 eHybrid", "GTE"],
    "Arteon": ["2.0 TSI", "2.0 TDI", "R"],
    "T-Cross": ["1.0 TSI", "1.5 TSI"],
    "T-Roc": ["1.0 TSI", "1.5 TSI", "2.0 TSI", "2.0 TDI", "R"],
    "Tiguan": ["1.5 TSI", "2.0 TSI", "2.0 TDI", "1.4 eHybrid", "R"],
    "Touareg": ["3.0 TSI", "3.0 TDI", "eHybrid", "R"],
  },
  // Japanese
  "Toyota": {
    "Yaris": ["1.0", "1.5", "1.5 Hybrid", "GR Yaris"],
    "Yaris Cross": ["1.5", "1.5 Hybrid", "GR Sport"],
    "Corolla": ["1.8 Hybrid", "2.0 Hybrid", "GR Sport"],
    "Camry": ["2.5 Hybrid"],
    "C-HR": ["1.8 Hybrid", "2.0 Hybrid", "GR Sport"],
    "RAV4": ["2.5 Hybrid", "2.5 Plug-in Hybrid", "Adventure"],
    "Supra": ["2.0", "3.0", "GR"],
    "GR86": ["Standard", "Premium"],
    "Land Cruiser": ["2.8 D-4D", "3.5 V6"],
    "Hilux": ["2.4 D-4D", "2.8 D-4D", "GR Sport"],
  },
  "Honda": {
    "Civic": ["1.5 VTEC", "2.0 VTEC", "e:HEV", "Type R"],
    "Accord": ["2.0 i-VTEC", "Hybrid"],
    "Jazz": ["1.5 e:HEV"],
    "HR-V": ["1.5 e:HEV"],
    "CR-V": ["1.5 VTEC", "2.0 e:HEV", "PHEV"],
    "ZR-V": ["2.0 e:HEV"],
    "e": ["Standard", "Advance"],
  },
  "Mazda": {
    "2": ["1.5 Skyactiv-G", "Hybrid"],
    "3": ["2.0 Skyactiv-G", "2.0 Skyactiv-X", "e-Skyactiv X"],
    "6": ["2.0 Skyactiv-G", "2.5 Skyactiv-G", "2.2 Skyactiv-D"],
    "CX-3": ["2.0 Skyactiv-G"],
    "CX-30": ["2.0 Skyactiv-G", "2.0 Skyactiv-X", "e-Skyactiv G"],
    "CX-5": ["2.0 Skyactiv-G", "2.5 Skyactiv-G", "2.2 Skyactiv-D"],
    "CX-60": ["2.5 e-Skyactiv G", "3.3 e-Skyactiv D", "PHEV"],
    "MX-5": ["1.5 Skyactiv-G", "2.0 Skyactiv-G", "RF"],
    "MX-30": ["e-Skyactiv", "R-EV"],
  },
  // Korean
  "Hyundai": {
    "i10": ["1.0", "1.2", "N Line"],
    "i20": ["1.0 T-GDi", "1.2", "N Line", "N"],
    "i30": ["1.0 T-GDi", "1.5 T-GDi", "1.6 CRDi", "N Line", "N"],
    "Ioniq 5": ["Standard Range", "Long Range", "N"],
    "Ioniq 6": ["Standard Range", "Long Range"],
    "Kona": ["1.0 T-GDi", "1.6 T-GDi", "Hybrid", "Electric", "N"],
    "Tucson": ["1.6 T-GDi", "1.6 CRDi", "Hybrid", "Plug-in Hybrid", "N Line"],
    "Santa Fe": ["2.2 CRDi", "Hybrid", "Plug-in Hybrid"],
  },
  "Kia": {
    "Picanto": ["1.0", "1.2", "GT-Line"],
    "Rio": ["1.0 T-GDi", "1.2", "GT-Line"],
    "Ceed": ["1.0 T-GDi", "1.5 T-GDi", "1.6 CRDi", "GT-Line", "GT"],
    "Proceed": ["1.5 T-GDi", "GT-Line", "GT"],
    "Stinger": ["2.0 T-GDi", "3.3 T-GDi GT"],
    "Sportage": ["1.6 T-GDi", "1.6 CRDi", "Hybrid", "Plug-in Hybrid", "GT-Line"],
    "Sorento": ["2.2 CRDi", "Hybrid", "Plug-in Hybrid"],
    "Niro": ["Hybrid", "Plug-in Hybrid", "EV"],
    "EV6": ["Standard Range", "Long Range", "GT-Line", "GT"],
    "EV9": ["Standard Range", "Long Range", "GT-Line"],
  },
  // Electric
  "Tesla": {
    "Model 3": ["Standard Range", "Long Range", "Performance", "Highland"],
    "Model S": ["Long Range", "Plaid"],
    "Model X": ["Long Range", "Plaid"],
    "Model Y": ["Standard Range", "Long Range", "Performance"],
  },
  "Rivian": {
    "R1T": ["Adventure", "Launch Edition", "Explore"],
    "R1S": ["Adventure", "Launch Edition", "Explore"],
  },
  "Lucid": {
    "Air": ["Pure", "Touring", "Grand Touring", "Sapphire"],
  },
  "Polestar": {
    "Polestar 2": ["Standard Range", "Long Range Single Motor", "Long Range Dual Motor", "BST Edition"],
    "Polestar 3": ["Long Range Dual Motor", "Performance"],
    "Polestar 4": ["Long Range Single Motor", "Long Range Dual Motor"],
  },
  // British
  "Jaguar": {
    "XE": ["P250", "P300", "D200"],
    "XF": ["P250", "P300", "D200"],
    "F-Type": ["P300", "P450", "P575", "R"],
    "E-Pace": ["P160", "P200", "P250", "P300"],
    "F-Pace": ["P250", "P340", "P400", "P550 SVR"],
    "I-Pace": ["EV320", "EV400"],
  },
  "Mini": {
    "Mini 3-Türer": ["One", "Cooper", "Cooper S", "John Cooper Works"],
    "Mini 5-Türer": ["One", "Cooper", "Cooper S", "John Cooper Works"],
    "Mini Cabrio": ["Cooper", "Cooper S", "John Cooper Works"],
    "Mini Clubman": ["Cooper", "Cooper S", "John Cooper Works"],
    "Mini Countryman": ["Cooper", "Cooper S", "Cooper SE", "John Cooper Works"],
    "Mini Electric": ["Standard", "SE"],
  },
}
